use fontspec/lualatex for the docs

diff --git a/doc/doit b/doc/doit
--- a/doc/doit
+++ b/doc/doit
@@ -19,7 +19,7 @@ for j in $set; do
 	\usepackage[a4paper,margin=20mm,noheadfoot]{geometry}
 	\pagestyle{empty}
 	\begin{document}\ttfamily
-	\fontsize{10}{12 pt}\selectfont
+	\fontsize{10}{12pt}\selectfont
 	\begin{verbatim}
 	EOD
 	grep -v "remove from source" "$j"
@@ -29,7 +29,7 @@ for j in $set; do
 	EOD
    } >s"$j".tex
 
-   echo x | pdflatex s"$j".tex &>/dev/null || die "pdflatex failed on s$j"
+   echo x | lualatex s"$j".tex &>/dev/null || die "lualatex failed on s$j"
    rm s"$j".{aux,tex,log}
    pdfcrop s"$j".pdf s"$j".pdf >& /dev/null
    # result
@@ -37,7 +37,16 @@ for j in $set; do
      [[ $j =~ [k-z] ]] && echo '\usepackage[papersize={56mm,40mm},showframe,margin=1mm,noheadfoot]{geometry}'
      cat <<-'EOD'
 	\usepackage{ctable}
-	\usepackage{txfonts}
+	\usepackage{fontspec}
+	\usepackage{microtype}
+	\makeatletter\def\MT@warn@unknown{}\makeatother
+	\setmainfont[Ligatures=TeX]{Fontin-Regular}[%
+	     ItalicFont=Fontin-Italic,
+             BoldFont=Fontin-Bold,
+             SmallCapsFont=Fontin-SmallCaps
+            ]
+	\setmonofont{DejaVuSansMono}[Scale=MatchLowercase]
+
 	\pagestyle{empty}
 	\parindent0pt
 	\begin{document}
@@ -45,7 +54,7 @@ for j in $set; do
      cat "$j"
      echo '\end{document}'
    } > "$j".tex
-   echo x | pdflatex "$j".tex &>/dev/null || die "pdflatex failed on $j"
+   echo x | lualatex "$j".tex &>/dev/null || die "lualatex failed on $j"
    rm "$j".{aux,tex,log}
    pdfcrop "$j".pdf "$j".pdf >& /dev/null
    printf "\r%d%%" $((n+=4))
diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -20,7 +20,7 @@ Options:
 
 = Description
 inst must be run in its own directory (|./inst|) and then does the following:
-- generates the documentation for isodoc,
+- generates the documentation,
 - installs ctable in one of your TeX trees: TEXMFMAIN, TEXMFLOCAL or TEXMFHOME. 
   The first one writable by you will chosen.
 - creates a zip file named |ctable-x.yy.zip| for upload to CTAN
@@ -109,11 +109,11 @@ makeall() {
    done
    cd .. || die
   
-   pdflatex "$job".dtx &>/dev/null || die "pdflatex failed on  $job.dtx"
+   lualatex "$job".dtx &>/dev/null || die "lualatex failed on  $job.dtx"
    if [ -f "$job".glo ]; then makeindex -q -s gglo.ist -o "$job".gls "$job".glo; fi
    if [ -f "$job".idx ]; then makeindex -q -s gind.ist -o "$job".ind "$job".idx; fi
-   pdflatex "$job".dtx &> /dev/null
-   pdflatex "$job".dtx &> /dev/null
+   lualatex "$job".dtx &> /dev/null
+   lualatex "$job".dtx &> /dev/null
 
 }
 
@@ -177,7 +177,7 @@ handle_options() {
    args=( "$@" )
 }
 
-excheck zip getopt pdflatex
+excheck zip getopt lualatex
 handle_options "$@"
 set -- "${args[@]}"
 [[ -z $1 ]] || die No arguments expected
