streamlined installation process, some fixes in doc

diff --git a/doc/doit b/doc/doit
--- a/doc/doit
+++ b/doc/doit
@@ -22,15 +22,16 @@ for j in $set; do
 	\fontsize{10}{12 pt}\selectfont
 	\begin{verbatim}
 	EOD
-	grep -v "remove from source" $j
+	grep -v "remove from source" "$j"
 	cat <<-'EOD'
 	\end{verbatim}
 	\end{document}
 	EOD
-   } >s$j.tex
+   } >s"$j".tex
 
-   mk --noprint --noview s$j.tex >/dev/null && mk -c s$j
-   pdfcrop s$j.pdf s$j.pdf >& /dev/null
+   echo x | pdflatex s"$j".tex &>/dev/null || die "pdflatex failed on s$j"
+   rm s"$j".{aux,tex,log}
+   pdfcrop s"$j".pdf s"$j".pdf >& /dev/null
    # result
    { echo '\documentclass[twoside]{article}'
      [[ $j =~ [k-z] ]] && echo '\usepackage[papersize={56mm,40mm},showframe,margin=1mm,noheadfoot]{geometry}'
@@ -41,9 +42,12 @@ for j in $set; do
 	\parindent0pt
 	\begin{document}
 	EOD
-     cat $j
+     cat "$j"
      echo '\end{document}'
-   } > $j.tex
-   mk --noprint --noview $j.tex >/dev/null && mk -c $j
-   pdfcrop $j.pdf $j.pdf >& /dev/null
+   } > "$j".tex
+   echo x | pdflatex "$j".tex &>/dev/null || die "pdflatex failed on $j"
+   rm "$j".{aux,tex,log}
+   pdfcrop "$j".pdf "$j".pdf >& /dev/null
+   printf "\r%d%%" $((n+=4))
 done
+echo -ne "\r    \r"
diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1,15 +1,10 @@
 #!/bin/bash
-    dtxname=ctable
-    dtxtype=package
-        ext=sty
-     delete=($dtxname.$ext README.tex doc/\*.tex)
- dtxversion=$(grep " v[0-9.]\+[a-z]\{0,1\} $dtxname $dtxtype" $dtxname.dtx |sed 's/.* v\([0-9.]\+[a-z]\{,1\}\) .*/\1/')
-executables=(mk texlog_extract zip getopt pdfseparate pdflatex)
+Version=1.01
+ Myname="${0##/}"
+    job=ctable
+    ext=sty
 
-    version=1.00
-     myname=$(basename $0)
-
-<<'DOC'
+:<<'DOC'
 = inst - install ctable
 
 = Synopsis
@@ -19,10 +14,9 @@ Without any options, inst installs ctable in the first writable
 TEXMFMAIN, TEXMFLOCAL or TEXMFHOME tree.
 
 Options:
--h,--help	print this help and exit
--H,--Help	print full documentation via less and exit
--V,--version	print version and exit
-
+-h|--help	print short help and exit
+-H|--Help	print full documentation and exit
+-V|--version	print version and exit
 
 = Description
 inst must be run in its own directory (|./inst|) and then does the following:
@@ -32,121 +26,161 @@ inst must be run in its own directory (|./inst|) and then does the following:
 - creates a zip file named |ctable-x.yy.zip| for upload to CTAN
 - cleans up
 
-= Author and copyright
-Author	Wybo Dekker
-Email	U{wybo@dekkerdocumenten.nl}{wybo@dekkerdocumenten.nl}
-License	Released under the U{www.gnu.org/copyleft/gpl.html}{GNU General Public License}
+= Author
+[Wybo Dekker](wybo@dekkerdocumenten.nl)
+
+= Copyright
+Released under the [GNU General Public License](www.gnu.org/copyleft/gpl.html)
 DOC
 
-    die() { echo -e "$myname: $Err$@$Nor" 1>&2; exit 1; }
-   help() { sed -n '/^= Synopsis/,/^= /p' $0|sed '1s/.*/Usage:/;/^= /d'; exit; }
-helpall() { sed -n '/^<<.DOC.$/,/^DOC$/p' $0|sed -n '1d;$d;p'|less; exit; }
-version() { echo $version; exit; }
-
-Nor='\e[0m'    # reset color	]
-Err='\e[31;1m' # light red	]
+REd='\e[38;5;9m' Nor='\e[0m'
+    die() { local i; for i; do echo -e "$Myname: $REd$i$Nor"; done 1>&2; exit 1; }
+helpsrt() { sed -n '/^= Synopsis/,/^= /p' "$0"|sed '1d;$d'; exit; }
+helpall() { sed -n "/^:<<'DOC'$/,/^DOC/p" "$0"|sed '1d;$d'|
+            less -P"$Myname-${Version/./·} (press h for help, q to quit)";exit; }
 
 setdir() { # create installation directory
    for i in MAIN LOCAL HOME; do
       tree=$(kpsewhich --expand-var \$TEXMF$i)
-      test -w $tree && break
+      test -w "$tree" && break
       tree=
    done
    [[ -n $tree ]] || die "Could not find a writable TeX tree"
-   insttex=${tree}/tex/latex/$dtxname
-   instsrc=$tree/source/latex/$dtxname
-   instdoc=$tree/doc/latex/$dtxname
+   insttex=${tree}/tex/latex/$job
+   instsrc=$tree/source/latex/$job
+   instdoc=$tree/doc/latex/$job
    mkdir -p $insttex || die could not create $insttex
    mkdir -p $instsrc || die could not create $instsrc
    mkdir -p $instdoc || die could not create $instdoc
 }
 
-testexecs() { # test presence of executables
-   for i in ${executables[*]}; do
-      type $i &> /dev/null || die executable $i not found
+:<<'DOC' #---------------------------------------------------------------------
+= excheck
+synopsis:	 excheck executable1 [executable2...]
+description:	check if all needed execs are there and getopt is GNU
+DOC
+#-------------------------------------------------------------------------------
+excheck() {
+   local ok=true i
+   ((BASH_VERSINFO>=4)) || die "Need bash version >= 4"
+   for i; do 
+      command -v "$i" > /dev/null && continue
+      Warn "Missing executable: $i"
+      ok=false
    done
-}
-
-readme() { # generate the README file
-sed -n '/^%<\*readme>/,/^%<\/readme>/p
-	/\\changes{v'$dtxversion'}/,/^% }/p' $dtxname.dtx  |
-sed    's/^%//;s/\\\\$//
-	/ Author:/i\
-Version:| '$dtxversion'
-	/<.readme>/d
-	/^ }/d
-	s/ \\changes.*/Changes in version '$dtxversion':/
-	s/$\\Rightarrow\$/=>/g
-	s/\\textbackslash/\\/g
-	s/\\text\(sl\|it\){\([^}]\+\)}/\/\2\//g		# \textsl{...} -> /.../
-	s/{\([^}]*\)}/\1/g 				# keep last, removes all {...}
-       ' >README
-  grep "Changes in version" README >/dev/null || die changes not detected
+   $ok || die
+   getopt -T 
+   [[ $? -ne 4 ]] && die "Your getopt is not GNU"
 }
 
 makeall() {
-   grep '%<\*install>' $dtxname.dtx >/dev/null && # for self-extracting dtx files
-      delete+=($dtxname.ins) ||
-      echo y |tex $dtxname.ins >/dev/null
+   local date d D v
+   tex $job.ins >/dev/null
+   # Now we have README.md; lets check the version and date were
+   # correctly set everywhere in the dtx-file:
+   version=$(sed  -n 's/|version | \(.*\)/\1/p' README.md)
+      date=$(sed  -n 's/|   date | \(.*\)/\1/p' README.md)
+   read -r d v < <(
+      sed -ne 's/^ *\[\([0-9/]\+\) v\([0-9.]\+[a-z]*\).*/\1 \2/p' "$job.dtx"
+   ) || die "package date and version not found in correct format"
+   D=$(sed -n 's/^% \\changes{v'"$version"'}{\(.*\)}{.*/\1/p' "$job.dtx")
+   [[ -n $D ]] || die "found no changes entry for version $version"
+   [[ $version == "$v" ]] ||
+      die "README version ($version) not equal to package version ($v)"
+   [[ $date == "$d" ]] ||
+      die "README date ($date) not equal to package date ($d)"
+   [[ $date == "$D" ]] ||
+      die "README date ($date) not equal to changes date ($D)"
+   
 
    # install any .ttf files
    mkdir -p ~/.fonts
    find doc -name '*.ttf' -exec cp {} ~/.fonts \;
    fc-cache ~/.fonts
 
-   readme # create the README file
-
    # compile all examples
-   cd doc
-   ln -sf ../$dtxname.sty || exit 1 # use the version to be installed
+   cd doc || die
+   ln -sf ../"$job".sty . || exit 1 # use the version to be installed
    for i in [0-9][0-9]?; do 
-      if [ ! -f $i.pdf -o ! -f s$i.pdf ]; then
+      if [[ ! -f $i.pdf ]] || [[ ! -f s$i.pdf ]]; then
          ./doit || exit 1
          break
       fi
    done
-   cd ..
+   cd .. || die
   
-   mk --noprint --noview $dtxname.dtx && mk -c $dtxname.dtx # make $dtxname.pdf
+   pdflatex "$job".dtx &>/dev/null || die "pdflatex failed on  $job.dtx"
+   if [ -f "$job".glo ]; then makeindex -q -s gglo.ist -o "$job".gls "$job".glo; fi
+   if [ -f "$job".idx ]; then makeindex -q -s gind.ist -o "$job".ind "$job".idx; fi
+   pdflatex "$job".dtx &> /dev/null
+   pdflatex "$job".dtx &> /dev/null
+
 }
 
 installall() {
    # install and cleanup
-   echo installing in $tree
-
-   rm -rf $insttex/* $instsrc/* $instdoc/*
-   find doc \( -type l -o -name '*.pdf' \) -delete
-   cp -f $dtxname.$ext $insttex
-   cp -a $dtxname.{ins,dtx} $instsrc
-   cp -a README inst $dtxname.pdf $instdoc
-   mktexlsr $tree 2>/dev/null
-   for i in ${delete[@]}; do rm -f $i; done 
-   cd ..
-   zipfile=$dtxname/$dtxname-$dtxversion.zip
-   rm -f $zipfile
-   zip -rq $zipfile $dtxname/* -x $dtxname/test\*
-   cd $dtxname
+   echo installing in "$tree"
+   # remove old versions from the tree:
+   rm -rf "${insttex:?}/*" "${instsrc:?}/*" "${instdoc:?}/*"
+   cp -f "$job.$ext" "$insttex"
+   cp -a "$job".{ins,dtx} "$instsrc"
+   cp -a "$job.pdf" "$instdoc"
+   mktexlsr "$tree" 2>/dev/null
+   rm -f "$job".{"$ext",aux,glo,gls,idx,ilg,ind,log,out,toc,pdf} doc/*.{tex,pdf,$ext}
+   tmp=$(mktemp -dt 'XXXXXXXXXX')
+   trap 'rm -rf $tmp' 0 1 2 15
+   mkdir "$tmp/$job"
+   cp -a README.md "$job".{dtx,ins} doc inst "$tmp/$job"
+   cd "$tmp" || die
+   zip -rq "$job-$version.zip" "$job"
+   cd ~- || die
+   mv "$tmp/$job-$version.zip" .
 }
 
-options=$(getopt \
-   -n $myname \
-   -o hHV \
-   -l help,Help,version \
-   -- "$@"
-) || exit 1
-eval set -- "$options"
-while [ $# -gt 0 ]; do
-   case $1 in
-   (-h|--help)	  help;;
-   (-H|--Help)	  helpall;;
-   (-V|--version) version;;
-   (--)		  shift;  break;;
-   (*)			  break;;
-   esac
-done
-[[ -z $1 ]] || die No arguments expected
+:<<'DOC' #----------------------------------------------------------------------
+= handle_options
+synopsis:	 handle_options "$@"
+description:	handle the options.
+globals used:	 Myname Version
+globals  set:	 args
+DOC
+#-------------------------------------------------------------------------------
+handle_options() {
+   local options
 
-testexecs
+   options=$(getopt \
+      -n "$Myname" \
+      -o hHV \
+      -l help,Help,version \
+      -- "$@"
+   ) || exit 1
+   eval set -- "$options"
+   while true; do
+      case $1 in
+      (-h|--help)    # print short help and exit
+	    helpsrt
+	    ;;
+      (-H|--Help)    # print full documentation and exit
+	    helpall
+	    ;;
+      (-V|--version) # print version and exit
+	    echo $Version
+	    exit
+	    ;;
+      (--)  shift
+	    break
+	    ;;
+      (*)   break
+	    ;;
+      esac
+   done
+   args=( "$@" )
+}
+
+excheck zip getopt pdflatex
+handle_options "$@"
+set -- "${args[@]}"
+[[ -z $1 ]] || die No arguments expected
 setdir
 makeall
 installall
